### ISSUE TITLE
Stack expensive as hell

### ISSUE THREAD

**Issue by Marboni** [aws-samples/aws-ecs-cicd-terraform#1]
Not everybody finishes the tutorial, some people put it aside for a while. Make sure that the tutorial mentions that the stack you create is expensive -- NAT Gateway is $0.045/hr, db.r4.2xlarge instances (do you really need them for the pet clinic?) are $0.96/hr. 

People abandoning this tutorial will be billed for hundreds bucks in the end of the month. Not nice.

**Comment by ibuchh** [comment]
We have added the instructions.

**Comment by rizblie** [comment]
README has been updated to include reminders. DB changed to m5.large.
